#!/bin/bash

cd `dirname $0`

rm -rf dist
export PYTHONHASHSEED=22
VERSION=`git describe --tags`
pyinstaller --noconfirm --ascii --name $VERSION osx.spec
hdiutil create -fs HFS+ -volname "Garlium" -srcfolder dist/Garlium.app dist/Garlium.dmg
